### ISSUE TITLE
Will this condition even return false?

### ISSUE THREAD

**Issue by joostf** [Frankwarnaar/minor-wafs#11]
https://github.com/Frankwarnaar/minor-wafs/blob/7f1c27371db48c15a945be83c2807c08e143cc9a/opdracht5%20-%20spa/assets/js/app.js#L31

**Comment by Frankwarnaar** [comment]
Yep. Imagine when the pages have anchor links  inside a page. You don't want to change the active section when the user changes to a route that does not exits. This way the user would end up seeing nothing, because al sections get hidden.
