### ISSUE TITLE
In app.js, could the toggle function be more concise

### ISSUE THREAD

**Issue by nickrttn** [Frankwarnaar/minor-wafs#4]
Could you come up with a way to toggle all of the classes inside the forEach loop for instance?

**Comment by Frankwarnaar** [comment]
In this case you might end with the wrong page if you open the SPA with another hash than the frontpage.

**Comment by Frankwarnaar** [comment]
You don't want that. If you open the SPA on another page than the frontpage, you want to show that content. So you will have to hide everything and show the active section.

**Comment by nickrttn** [comment]
You could still do that in a single loop.

**Comment by Frankwarnaar** [comment]
Did that ;)
